name: Analyse code

on:
  push:
    branches: [ $default-branch ]
    
  pull_request:
    branches: [ $default-branch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse-workflow-check-code:
    name: Run code analyser
    uses: ehennestad/matbox/.github/workflows/reusable_check_code.yml@v0.9
